name: project
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  path:
  sqflite:
  sqflite_common_ffi: ^2.2.5
  audioplayers: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/logo.png
   - assets/usuario.png
   - assets/rap.jpg
   - assets/sertanejo.png
   - assets/luan_santana.png
   - assets/seuastral.jpeg
   - assets/anjoscantam.jpeg
   - assets/assumibrasil.jpeg
   - assets/vidaloka.jpeg
   - assets/leal.jpeg
   - assets/bomlugar.jpeg
   - assets/anjoscantam.mp3
  # fonts:
  
